name: PR Bundle Check

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  bundle-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@cmu-sei'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.nvmrc') }}

    # - name: Install dependencies
    #   run: npm install

    # - name: Prepare .nuxt directory
    #   run: npm run dev:prepare

    # - name: Lint components
    #   run: npm run lint

    - name: Publish dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm publish --tag beta --dry-run
